version: 2.1
workflows:
  API-Workflow:
    jobs:
      - Build
      - Unit Test:
          requires:
            - Build
      - Validation Test:
          requires:
            - Build
      - Implementation Test:
          requires:
            - Validation Test
      - Backend Integration Test:
          requires:
            - Validation Test
      - Frontend Integration Test:
          requires:
            - Validation Test
      - Stage:
          requires:
            - Unit Test
            - Validation Test
            - Implementation Test
            - Backend Integration Test
            - Frontend Integration Test
      - Approve Deploy:
          type: approval
          requires:
            - Stage
      - Approve Test Shutdown:
          type: approval
          requires:
            - Stage
      - Deploy:
          requires:
            - Approve Deploy
      - Shutdown Test:
          requires:
            - Approve Test Shutdown
  KarrLab:
    jobs:
      - karrlab

executors:
  karr_lab_build_env:
    docker:
      - image: karrlab/wc_env_dependencies:latest
    working_directory: /root/project
  setup_env:
    working_directory: /root/API/
    docker:
      - image: python:3.6
  api_test_env:
    working_directory: /root/API/
    docker:
      - image: python:3.6
  query_test_env:
    working_directory: /root/Query
    docker:
      - image: python:3.6

testJob: &testJob
  working_directory: /root/build
  docker:
    - image: python:3.6
  steps:
    - attach_workspace:
        at: /
    - checkout
    - run:
        name: Test Run
        command: echo "Test Run"
jobs:
  karrlab:
    executor: karr_lab_build_env
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-{{ arch }}-{{ .Branch }}-{{ checksum "/etc/docker-image-tag" }}-{{ checksum
              "requirements.txt" }}
      - run:
          name: Install pkg_utils (Python 3)
          command: pip3 install -U git+https://github.com/KarrLab/pkg_utils.git#egg=pkg_utils
      - run:
          name: Install karr_lab_build_utils (Python 3)
          command: |
            pip3 install -U git+https://github.com/KarrLab/sphinxcontrib-googleanalytics.git#egg=sphinxcontrib_googleanalytics
            pip3 install -U git+https://github.com/KarrLab/wc_utils.git#egg=wc_utils[all]
            pip3 install -U git+https://github.com/KarrLab/karr_lab_build_utils.git#egg=karr_lab_build_utils[all]
      - run:
          name: Install package configuration files including credentials
          command: karr_lab_build_utils3 download-install-package-config-files
      - run:
          name: Setup Python environment
          command: |
            if [[ -f .circleci/requirements.txt ]]; then
              while IFS="" read -r line || [ -n "$line" ]; do
                if [[ ! -z "$line" ]] && [[ ! "$line" =~ ^# ]]; then
                  pip3 install -U "$line"
                fi
              done < .circleci/requirements.txt
            fi
      - run:
          name: Install package (Python 3)
          command: pip3 install -U -e .[all]
      - save_cache:
          key:
            v2-{{ arch }}-{{ .Branch }}-{{ checksum "/etc/docker-image-tag" }}-{{
            checksum "requirements.txt" }}
          paths:
            - /usr/local/lib/python3.6/site-packages
      - run:
          name: Test code
          command: |
            set +e

            karr_lab_build_utils3 run-tests --with-xunit --with-coverage
            TEST_EXIT_CODE_PY3=$?

            # Calculate exit code and save to file for reading by the next step
            if [[ $TEST_EXIT_CODE_PY3 -eq 0 ]]; then
              echo "0" > TEST_EXIT_CODE
              exit 0
            else
              echo "0" > TEST_EXIT_CODE
              exit 1
            fi
      - run:
          name: Generate reports, archive results, and send notifications
          when: always
          command: |
            if [[ -f TEST_EXIT_CODE ]]; then
              INSTALLATION_EXIT_CODE=0
              TEST_EXIT_CODE=$(<TEST_EXIT_CODE)
            else
              INSTALLATION_EXIT_CODE=1
              TEST_EXIT_CODE=1
            fi

            karr_lab_build_utils3 do-post-test-tasks $INSTALLATION_EXIT_CODE $TEST_EXIT_CODE
      - store_test_results:
          path: /root/project/tests/reports
      - store_artifacts:
          path: /root/project/tests/reports
          destination: reports
      - store_artifacts:
          path: /root/.wc/log
          destination: log
      - store_artifacts:
          path: /root/project/docs/_build/html
          destination: docs
  Build:
    executor: setup_env
    steps:
      #Get package
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{.Branch}}-
      - checkout
      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - .
      #Get Test dependencies
      - restore_cache:
          key: test-dependencies-v1-{{arch}}-{{ .Branch }}-{{ checksum "tests/requirements.txt"}}
      - run:
          name: Install test dependencies
          command: pip3 install -r tests/requirements.txt
      - save_cache:
          key: test-dependencies-v1-{{arch}}-{{ .Branch }}-{{ checksum "tests/requirements.txt"}}
          paths:
            - /usr/local/lib/python3.6/site-packages
            - /usr/local/bin/
      #Get main dependencies
      - restore_cache:
          key: dependencies-v1-{{ arch }}-{{ .Branch }}-{{ checksum "requirements.txt"}}
      - run:
          name: Install Package Dependencies
          command: pip3 install -r requirements.txt
      - save_cache:
          key:
            dependencies-v1-{{ arch }}-{{ .Branch }}-{{ checksum "requirements.txt"
            }}
          paths:
            - /usr/local/lib/python3.6/site-packages
            - /usr/local/bin
      # Install circle specific dependencies
      - run:
          name: Install Test Packages
          command: |
            if [[ -f .circleci/requirements.txt ]]; then
              while IFS="" read -r line || [ -n "$line" ]; do
                if [[ ! -z "$line" ]] && [[ ! "$line" =~ ^# ]]; then
                  pip3 install -U "$line"
                fi
              done < .circleci/requirements.txt
            fi
      #Get build configs
      - add_ssh_keys:
          fingerprints:
            - "d5:32:b5:ab:5c:f6:ba:f7:31:d0:98:2e:be:81:0c:70"
      - run:
          name: Get Build config
          command: git clone git@github.com:KarrLab/karr_lab_build_config.git ../.wc

      - persist_to_workspace:
          root: /
          paths:
            - usr/local/lib/python3.6/site-packages
            - usr/local/bin
            - root/API/
            - root/.wc
  Unit Test:
    executor: setup_env
    steps:
      - attach_workspace:
          at: /
      - checkout
      - run:
          name: Install package (Python 3)
          command: pip3 install -U -e .
      - run:
          name: Run Tests
          command: pytest
  Validation Test:
    <<: *testJob
  Implementation Test:
    <<: *testJob
  Backend Integration Test:
    <<: *testJob
  Frontend Integration Test:
    <<: *testJob
  Stage:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: "Install Heroku CLI, if necessary"
          command: |
            if [[ $(command -v heroku) == "" ]]; then
              curl https://cli-assets.heroku.com/install.sh | sh
            else
              echo "Heroku is already installed. No operation was performed."
            fi
      - run:
          name: Enable Heroku Stage Container
          command: heroku ps:scale web=1 -a $HEROKU_APP_NAME_STAGE
      - run:
          name: Stage Master to Heroku
          command: |
            git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_STAGE.git master
  Deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: "Install Heroku CLI, if necessary"
          command: |
            if [[ $(command -v heroku) == "" ]]; then
              curl https://cli-assets.heroku.com/install.sh | sh
            else
              echo "Heroku is already installed. No operation was performed."
            fi
      - run:
          name: Disable Heroku Stage Container
          command: |
            heroku ps:stop -a $HEROKU_APP_NAME_STAGE web
            heroku ps:scale web=0 -a $HEROKU_APP_NAME_STAGE
      - run:
          name: Deploy Master to Heroku
          command: |
            git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
  Shutdown Test:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run:
          name: "Install Heroku CLI, if necessary"
          command: |
            if [[ $(command -v heroku) == "" ]]; then
              curl https://cli-assets.heroku.com/install.sh | sh
            else
              echo "Heroku is already installed. No operation was performed."
            fi
      - run:
          name: Disable Heroku Stage Container
          command: heroku ps:scale web=0 -a $HEROKU_APP_NAME_STAGE
