openapi: 3.0.1
info:
  title: Datanator API
  version: 1.0.0
  description:
    A REST API for the <a href="https://datanator.info" target="_blank" 
    rel="noopener noreferrer">Datanator integrated database</a> of molecular data for 
    modeling the biochemistry of cells. The API can be used to find data for modeling
    cells such as the concentrations of metabolites, abundances of proteins, and rate
    constants of reactions. The API is compliant with the <a href="https://www.openapis.org/" 
    target="_blank" rel="noopener noreferrer">OpenAPI 3 standard</a>.
  contact:
    name: Karr Lab
    email: info@karrlab.org
    url: https://datanator.info/
servers:
  - description: The default server
    url: /
  - description: The Datanator server
    url: https://api.datanator.info
  - description: The Datanator test server
    url: https://testapi.datanator.info
tags:
  - name: Datanator
    description: Requests related to the database itself
  - name: Metabolites
    description: Requests for information about metabolites, including conentrations
  - name: Proteins
    description: Requests for information about proteins, enzymes, and protein complexes
  - name: Reactions
    description: Requests for information on reactions, including kinetic paramters
  - name: RNA
    description: Requests for information on RNA
  - name: Kegg
    description: Requests for information on KEGG database.
  - name: NCBI Taxonomy
    description: Requests for querying the taxonomic tree.

paths:
  /:
    $ref: paths/root.yaml
  /status/:
    $ref: paths/datanator.yaml
  /metabolites/:
    $ref: paths/metabolites.yaml#/root
  /metabolites/concentrations/:
    $ref: paths/metabolites.yaml#/concentrations
  /metabolites/summary/concentration_count/:
    $ref: paths/metabolites.yaml#/num_conc
  /metabolites/meta/:
    $ref: paths/metabolites.yaml#/meta
  /metabolites/concentration/:
    $ref: paths/metabolites.yaml#/concentration
  /metabolites/concentration_only/:
    $ref: paths/metabolites.yaml#/concentration_only
  /proteins/precise_abundance/:
    $ref: paths/proteins.yaml#/precise_abundance
  /proteins/proximity_abundance/:
    $ref: paths/proteins.yaml#/proximity_abundance
  /proteins/proximity_abundance/proximity_abundance_kegg/:
    $ref: paths/proteins.yaml#/proximity_abundance_kegg
  /proteins/meta/meta_combo/:
    $ref: paths/proteins.yaml#/meta/meta_combo
  /proteins/meta/meta_single/:
    $ref: paths/proteins.yaml#/meta/meta_single
  /proteins/summary/num_protein/:
    $ref: paths/proteins.yaml#/summary/num_protein
  /proteins/summary/num_organism/:
    $ref: paths/proteins.yaml#/summary/num_organism
  /proteins/summary/num_abundances/:
    $ref: paths/proteins.yaml#/summary/num_abundances
  /proteins/similar_protein/refseq/:
    $ref: paths/proteins.yaml#/similar_protein/refseq
  /proteins/related/related_reactions/:
    $ref: paths/proteins.yaml#/related/related_reactions/
  /reactions/kinlaw_by_rxn/:
    $ref: paths/reactions.yaml#/kinlaw_by_rxn/
  /reactions/kinlaw_by_name/:
    $ref: paths/reactions.yaml#/kinlaw_by_name/
  /reactions/kinlaw_doc/:
    $ref: paths/reactions.yaml#/kinlaw_doc/
  /reactions/kinlaw_doc/with_prm/:
    $ref: paths/reactions.yaml#/with_prm
  /reactions/kinlaw_entry/:
    $ref: paths/reactions.yaml#/kinlaw_entry/
  /reactions/summary/num_organism/:
    $ref: paths/reactions.yaml#/summary/num_organism
  /reactions/summary/num_entries/:
    $ref: paths/reactions.yaml#/summary/num_entries
  /rna/halflife/get_info_by_name/:
    $ref: paths/rna.yaml#/get_info_by_name/
  /rna/halflife/get_info_by_ko/:
    $ref: paths/rna.yaml#/get_info_by_ko/
  /rna/meta/get_total_docs/:
    $ref: paths/rna.yaml#/get_total_docs/
  /taxon/canon_rank_distance/:
    $ref: paths/taxon.yaml#/canon_rank_distance/
  /taxon/canon_rank_distance_by_name/:
    $ref: paths/taxon.yaml#/canon_rank_distance_by_name/
  /taxon/is_child/:
    $ref: paths/taxon.yaml#/is_child/
  /taxon/canon_rank_common_distance/:
    $ref: paths/taxon.yaml#/canon_rank_common_distance/
  /ftx/text_search/:
    $ref: paths/ftx.yaml#/text_search/
  /ftx/text_search/indices_in_page/:
    $ref: paths/ftx.yaml#/indices_in_page/
  /ftx/text_search/num_of_index/:
    $ref: paths/ftx.yaml#/num_of_index/
  /ftx/text_search/protein_ranked_by_ko/:
    $ref: paths/ftx.yaml#/protein_ranked_by_ko/
  /ftx/text_search/frontend_num_of_index/:
    $ref: paths/ftx.yaml#/frontend_num_of_index/
  /kegg/get_meta/:
    $ref: paths/kegg.yaml#/get_meta/
    
components:
  schemas:
    Projection:
      $ref: ./schemas/projection.yaml
    Metabolite:
      $ref: ./schemas/metabolites/metabolite.yaml
    MetaboliteConcentration:
      $ref: ./schemas/metabolites/metabolite_concentration.yaml
    MetaboliteMeta:
      $ref: ./schemas/metabolites/metabolites_meta.yaml
    Observation:
      $ref: ./schemas/metabolites/observation.yaml
    Reaction:
      $ref: ./schemas/metabolites/reaction.yaml
    ProteinAbundance:
      $ref: ./schemas/proteins/singular_protein_abundance.yaml
    ProximityProteinAbundance:
      $ref: ./schemas/proteins/proximity_protein_abundance.yaml
    ProteinMetaCombo:
      $ref: ./schemas/proteins/protein_meta_combo.yaml
    ProteinMetaSingle:
      $ref: ./schemas/proteins/protein_meta_single.yaml
    RxnCompartment:
      $ref: ./schemas/reactions/compartment.yaml
    RxnEnzyme:
      $ref: ./schemas/reactions/enzyme.yaml
    RxnResource:
      $ref: ./schemas/reactions/resource.yaml
    RxnComprehensive:
      $ref: ./schemas/reactions/comprehensive.yaml
    RxnError:
      $ref: ./schemas/reactions/error.yaml
    RxnEntryId:
      $ref: ./schemas/reactions/kinlaw_entry.yaml
    RnaHalflives:
      $ref: ./schemas/RNA/rna_halflives.yaml
    RnaHalflifeDoc:
      $ref: ./schemas/RNA/halflife_doc.yaml
    TxnCanonRankDistance:
      $ref: ./schemas/taxon/canon_rank_distance.yaml
    FtxShards:
      $ref: ./schemas/ftx/shards.yaml
    FtxHitsObj:
      $ref: ./schemas/ftx/hits_obj.yaml
    FtxHitsArray:
      $ref: ./schemas/ftx/hits_array.yaml
    FtxTransHits:
      $ref: ./schemas/ftx/transformed_hits.yaml
    FtxHitsInPage:
      $ref: ./schemas/ftx/indices_in_page.yaml
    FtxProteinByKo:
      $ref: ./schemas/ftx/protein_ranked_by_ko.yaml
    FTX:
      $ref: ./schemas/ftx/ftx.yaml
    KeggMetaDoc:
      $ref: ./schemas/kegg/kegg_meta_doc.yaml
    GeneralError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
  parameters:
    skipParam:
      name: skip
      in: query
      description: number of items to skip
      required: true
      schema:
        type: integer
        format: int32
    limitParam:
      name: limit
      in: query
      description: max records to return
      required: true
      schema:
        type: integer
        format: int32
  responses:
    NotFound:
      description: Entity not found.
    IllegalInput:
      description: Illegal input for operation.
    GeneralError:
      description: General Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/GeneralError"
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://example.org/api/oauth/dialog
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
